### ISSUE TITLE
Please change to an open or free license

### ISSUE THREAD

**Issue by viccuad** [SUSE/recipebook#38]
Hi, this idea is great!

Sadly, the current license, `Creative Commons Attribution-NoDerivs 3.0 Unported`, is neither Open Source nor Free Software. This is because it doesn't allow non-derivative works.

Could it be changed to an Open Source or Free Software license?
I propose `CC BY-SA 3.0`, https://creativecommons.org/licenses/by-sa/3.0/, which has a "share-alike" clause instead of a "non-derivative" clause.

(note that one needs the approval of all the contributors for such a change).

**Comment by dcermak** [comment]
I have no objections to the relicensing, albeit I would suggest to go with version 4.0 instead of 3.0.

What about the rest?
- [x] @asettle 
- [ ] @smarlowucf
- [x] @ml8mr
- [ ] @aosthof
- [ ] @SheilaghM
- [ ] @rsimai
- [x] @jeremy-moffitt
- [x] @bmwiedemann
- [ ] @KeithMnemonic

**Comment by bmwiedemann** [comment]
I'm fine with any FLOSS license.
Also worth reading:
https://paleoflourish.com/recipe-copyright/ 

> the court ruled that both the ingredients and the directions were not protected by copyright

That leaves just the collective copyright - similar to openSUSE and SLE. And maybe copyright on images.

**Comment by ml8mr** [comment]
I'm also fine with any FLOSS license.

**Comment by jeremy-moffitt** [comment]
I didn't realize the limitations on the initial license, I had just started from the license we used in our SOC release notes. I'm all for correcting it.

**Comment by asettle** [comment]
Sounds good to me :clap:  thanks for bringing this up. @jeremy-moffitt I'm surprised that's the license for the release notes?!

**Comment by jeremy-moffitt** [comment]
> Sounds good to me  thanks for bringing this up. @jeremy-moffitt I'm surprised that's the license for the release notes?!

https://github.com/SUSE/release-notes-suse-openstack-cloud/blob/suse-openstack-cloud-9/LICENSE 

:man_shrugging:  ... maybe thats why the product died ;-)
